#44 最初の画面へ戻るボタン完成
NJ-WebAppTeamDev/koriyama-web-app pull request #47
Opened 2024-08-12 00:51 UTC by nakagawahina

2024-08-12 00:54 UTC, KadoProG commented
VSCodeにPrettierは入っているでしょうか？
最後の行は１つ改行を入れないとgitの管理で不十分な形となってしまいます。

もしprettierが入っていない場合は`yarn prettier`でも同様にフォーマットが可能です。

<img width="255" alt="スクリーンショット 2024-08-12 9 52 54" src="https://github.com/user-attachments/assets/c943ac27-0626-4fbb-9e39-6fe36459e306">

2024-08-12 00:55 UTC, KadoProG requested changes
画像で添付した点を修正して、もう一度リクエストください。

2024-08-12 01:00 UTC, nakagawahina commented
yarn prettier書いたのですがエラーがでてしまいました。これはこのコマンドをたたく場所が違いますか？

![image](https://github.com/user-attachments/assets/84b1acbc-3202-47fd-83f2-073abe9b983b)

2024-08-12 01:33 UTC, KadoProG commented
@nakagawahina 
> yarn prettier書いたのですがエラーがでてしまいました。これはこのコマンドをたたく場所が違いますか？
> 
> ![image](https://private-user-images.githubusercontent.com/152489046/356916310-84b1acbc-3202-47fd-83f2-073abe9b983b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjY2NjEsIm5iZiI6MTcyMzQyNjM2MSwicGF0aCI6Ii8xNTI0ODkwNDYvMzU2OTE2MzEwLTg0YjFhY2JjLTMyMDItNDdmZC04M2YyLTA3M2FiZTliOTgzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTMyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjMwODcwZTAzNzk3M2Q4M2I5NGI3NTFmMjEwNDQ5YjJjMTkwZDU2MGZhOWJhYTc1ZTRmY2NmMjk2ODJiOGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S8FBQ7Utn0mLLn0ScPUq_peaJupo12FxpA0OH8x9EYA)

そうですね。確かfrontendのページにpackage.jsonがあると思うので、そこで実行してみてください。

2024-08-12 01:43 UTC, nakagawahina commented
cd package.jsonで移動してからyarn prettierをたたくということだと思ったのですがエラーが出てしまいました。私の認識が間違っているのでしょうか？
![image](https://github.com/user-attachments/assets/2d9595ea-f032-46da-97a7-4783418dd4fe)

2024-08-12 01:58 UTC, KadoProG commented
`cd frontend` `yarn prettier`です。

2024-08-12 02:05 UTC, nakagawahina commented
そのように打っているつもりなのですがエラーがでてしまいます。本当にお手数おかけして申し訳ございませんが、どのように修正すればよいか教えていただけますでしょうか？
![image](https://github.com/user-attachments/assets/976fba39-7659-4dfc-8a00-6e4787bfa218)

2024-08-12 04:47 UTC, KadoProG commented
一度yarnと打ってpackageをインストールしてもう一度やってみてください

2024-08-12 10:00 UTC, nakagawahina commented
遅くなってしまい申し訳ございません。教えていただいたとおりにやったらできました。ありがとうございます。
リクエストさせていただいたので、お時間あるときにご確認お願いします。

2024-09-13 08:39 UTC, KadoProG approved these changes

2024-09-18 23:34 UTC, merged